### ISSUE TITLE
[Android device] entire screen goes blank on 

### ISSUE THREAD

**Issue by good2hear** [nlt2390/react-native-view-more-text#1]
Hi there,
Thanks for the plugin!!

When I tested with scrollView in android device, 'View More' worked fine but when I tapped on 'View Less', entire screen went blank; I had to scroll to see the original view. 

It works fine with iOS device.

any idea what might be causing this? 
Thanks!!

**Comment by nlt2390** [comment]
@good2hear Hi, can u provide ur code & android version ? I just tested on android 5.1.0 but didn't see it.

**Comment by good2hear** [comment]
@nlt2390 thanks for reply! the code I used is pretty much the same as your sample code.
did you run it with android device? I tested with Samsung galaxy S7.

**Comment by nlt2390** [comment]
@good2hear Yes I did some tests on Android 4.1.1, 5.1.0, 6.0.0. Still cannot replicate that.

**Comment by good2hear** [comment]
@nlt2390 that's weird.. I tried with other devices and it's the same
did you try with scrollView where it got scrolled down by pressing renderViewMore? 
it's just not scrolling back up when pressing renderViewLess right away; i have to scroll it to see it scrolled up.

**Comment by nlt2390** [comment]
@good2hear Hi, I understand your issue now. It's about the `<ScrollView>` **not auto-scroll up**. Unfortunately, I couldn't find a way to touch the `<ScrollView>` wrapping `<ViewMoreText>`.

Therefore, I resolved the problem by adding 2 callbacks: afterCollapse/afterExpand. You can do sth like this:

```
let example = React.createClass({
  afterCollapse(){
    if(this.refs['ScrolLView']){
      this.refs['ScrolLView'].scrollTo({y: 0});
    }
  },
  render(){
    return(
      <ScrollView ref='ScrolLView'>
        <ViewMoreText
            afterCollapse={this.afterCollapse} ... >
            ...
        </ViewMoreText>
      </ScrollView>
    )
  }
})
```

Please update the plugin to 1.1.2 and try it. Hope this helps!

**Comment by good2hear** [comment]
@nlt2390 that did a trick!! thanks for the help!! :))
