### ISSUE TITLE
Incorrect height on a collapsible panel with absolute position

### ISSUE THREAD

**Issue by stsiushkevich** [nlt2390/react-native-view-more-text#11]
A have a collapsible pannel with absolute position. When I place ViewMoreText on this panel it has incorrect height((
<img width="376" alt="screen shot 2017-12-27 at 16 46 20" src="https://user-images.githubusercontent.com/12151060/34383320-8d0a0a64-eb25-11e7-81a9-af532e87c155.png">

**Comment by nlt2390** [comment]
@stsiushkevich Hi, I've tried on my side but cannot replicate this issue. Could you post ur code here ?

**Comment by stsiushkevich** [comment]
try to use 'react-native-collapsible' plugin and position: absolute on it

**Comment by stsiushkevich** [comment]
```javascript
const styles = StyleSheet.create({
  collapsiblePanelWrapper:{
    backgroundColor: 'white',
    position: 'absolute',
    zIndex: 1,
    left: 0,
    right: 0,
    bottom: 0
  }
})

function MarketplacesCollapsiblePanel (props) {
  const { isCollapsed, maxHeight, marketplaces, onSelect } = props

  let content = null
  if (isNotEmpty(marketplaces)) {
    const rows = _.map(marketplaces, (o, i) => {
      return (
        <View>
              <ViewMore numberOfLines={1}>
                  <Text style={style}>Test big text. Test big text. Test big text. Test big text. </Text>
              </ViewMore>
              <ViewMore numberOfLines={1}>
                  <Text style={style}>Test big text. Test big text. Test big text. Test big text. 
                   Test big text. Test big text. Test big text. Test big text. </Text>
              </ViewMore>
        </View>
      )
    })
  }
  return (
    <View style={styles.collapsiblePanelWrapper}>
      <Collapsible collapsed={isCollapsed} duration={500}>
        <View>{rows}</View>
      </Collapsible>
    </View>
  )
}
```

**Comment by stsiushkevich** [comment]
I have a similar code. I think you will be able to reproduce my issue.

**Comment by nlt2390** [comment]
@stsiushkevich Hi, thanks a lot for raising this issue. The issue is not about "position: 'absolute'", it's   about 2 <ViewMoreText><ViewMoreText> rendering at the same time.
To fix this, I've added 1 more attribute "renderTimeout" to prevent simultaneous rendering.
In this case:

```javascript
     let rows = _.map([1,2,3], (o, i) => {
      return (
        <View style={styles.row}>
              <ViewMore numberOfLines={1} renderTimeout={50 * i}>
                  <Text style={style}>Test big text. Test big text. Test big text. Test big text. 
                   Test big text. Test big text. Test big text. Test big text. </Text>
              </ViewMore>
              <ViewMore numberOfLines={1} renderTimeout={50 * i + 100}>
                  <Text style={style}>Test big text. Test big text. Test big text. Test big text. 
                   Test big text. Test big text. Test big text. Test big text. </Text>
              </ViewMore>
        </View>
      )
    })
```

Plz update the plugin and try again. Let me know if this issue is fixed.
Thanks!

**Comment by stsiushkevich** [comment]
Cool!!!! Thank you!

**Comment by stsiushkevich** [comment]
I'll try tomorrow and close this issue if all will be good

**Comment by stsiushkevich** [comment]
Your decision is working. But I must set 0, 300, 500 timeouts for normal work. So user can see a significant duration(((

**Comment by nlt2390** [comment]
Yes I know it's slow down. Initially I made this just for 1 simple rendering, not to be rendered multiple  times like this. I'll try to update this when I have time.
For now, if u dont want to let users see the rendering process, u can set opacity = 0 to wrapper div, then set it back to 1 after 2-3 seconds.
Hope this helps.

**Comment by stsiushkevich** [comment]
Ok. I want your changes. You can close this issue I think.

**Comment by nlt2390** [comment]
ok thanks. Have a nice day.
