### ISSUE TITLE
textStyle propType displays warning for arrays

### ISSUE THREAD

**Issue by tyricec** [nlt2390/react-native-view-more-text#13]
In my example I am passing in an array as prop for textStyle:

```jsx
const defaultStyle = { color: '#000000' };
const appTheme = { color: '#00ff00' };
const userTheme = { color: '#0000ff' };

// .....
<ViewMoreText
  textStyle={[defaultStyle, appTheme, userTheme]}
>
  // ...
</ViewMoreText>
```

<img width="368" alt="screen shot 2018-01-05 at 11 18 24 am" src="https://user-images.githubusercontent.com/3968741/34625560-03f74b5c-f20e-11e7-80b2-96563a3ae67a.png">

React-Native allows to pass styles as an array to give effect similar to css (cascading).

Will create pull request if I'm able what the correct propType for textStyle should be.

**Comment by tyricec** [comment]
Any particular reason this was changed to PropTypes.object for 1.4.0 update?

https://github.com/nlt2390/react-native-view-more-text/blob/79aa729fcf33d5322fca029a595b407908c7a141/index.js#L151

**Comment by nlt2390** [comment]
@tyricec U r right. Let me update.

**Comment by nlt2390** [comment]
@tyricec Updated. #12

**Comment by tyricec** [comment]
Thanks
