### ISSUE TITLE
How to hide "read more" when number of lines is under a certain number?

### ISSUE THREAD

**Issue by zhaonian** [nlt2390/react-native-view-more-text#14]
How to hide "read more" when the actual number of lines is under a certain number?

I did something like this:
```
<ViewMoreText
    numberOfLines={3}
    renderViewMore={this._renderViewMore}
    renderViewLess={this._renderViewLess}
    textStyle={styles.caption}
>
        <Text>{this.props.caption}</Text>
</ViewMoreText>


_renderViewMore(onPress) {
        return (
                <Text
                        style={styles.viewMore}
                        onPress={onPress}
                >
                        View more
                </Text>
        );
}
```

**Comment by nlt2390** [comment]
@zhaonian  Hi, as in ur example, if the rendered text has number of lines < 3, the "read more" button won't show.

**Comment by zhaonian** [comment]
@nlt2390 thanks for your reply! 
Most of the times it works just fine, but for some reason, it shows the 'View More' button even when the actual number of lines is under 3. Im not sure why. :cold_sweat:

**Comment by nlt2390** [comment]
@zhaonian may be something in ur component styles makes <ViewMoreText> miscalculating the number the text lines, u can try to change it.
