### ISSUE TITLE
The heigh delay during render of list 

### ISSUE THREAD

**Issue by stsiushkevich** [nlt2390/react-native-view-more-text#15]
This issue is related with #11. When you added `renderTimeout` prop component has began working
more slowly. When I use it on the list(more than 1 view-more component in one row) on collapsible panel I must to set a big delay (about 300, 500, 700) that component will render correctly.
<img width="377" alt="screen shot 2018-01-17 at 11 35 21" src="https://user-images.githubusercontent.com/12151060/35033149-96b737e8-fb7a-11e7-995f-97d0601cb6f1.png">

In this screen all 3 labels in the row use view-more-text component.

**Comment by nlt2390** [comment]
I see, let me try to find a way

**Comment by nlt2390** [comment]
@stsiushkevich Hi, I add a fix for this in version 1.4.3. plz reinstall this plugin and help me test.
Let me know whether this issue still persist.

**Comment by stsiushkevich** [comment]
I have installed fix, but we have old issue
<img width="372" alt="screen shot 2018-01-18 at 14 59 56" src="https://user-images.githubusercontent.com/12151060/35097279-818f44d2-fc60-11e7-92e9-824e29576a26.png">

I have revised the code of collapsible panel and discovered that it use node.measure(). So your component is incompatible with it. This panel requires nodes with static height only.(((

**Comment by stsiushkevich** [comment]
I have revised the code of collapsible-panel and discovered this code:
```javascript
  _measureContent(callback) {
    this.setState(
      {
        measuring: true,
      },
      () => {
        requestAnimationFrame(() => {
          if (!this.contentHandle) {
            this.setState(
              {
                measuring: false,
              },
              () => callback(this.props.collapsedHeight)
            );
          } else {
            this.contentHandle.getNode().measure((x, y, width, height) => {
              this.setState(
                {
                  measuring: false,
                  measured: true,
                  contentHeight: height,
                },
                () => callback(height)
              );
            });
          }
        });
      }
    );
  }
```
So your component and collapsible-pannel aren't compatible. I decided to implement my own component, like:
```<ViewMore linesThresholdNumber={2} lineHeight={20} text="My Big Text..."/>```. It will be more primitive of course, but wouldn't have this issue.

**Comment by nlt2390** [comment]
You can have a quick look on my new commit. Basically, I just set the initial position of <ViewMoreText> to 'absolute' before measuring the height, then change it back to 'relative' after rendering is finish. This prevents the first <ViewMoreText> pushes the content down and makes other <ViewMoreText> calculate wrong height.
Hope this idea can help.

**Comment by stsiushkevich** [comment]
Ok. I wil try.
