### ISSUE TITLE
Text inside ViewMore component flickers

### ISSUE THREAD

**Issue by Thanmai-C** [nlt2390/react-native-view-more-text#16]
Hi,
I have a description text that can vary so i have enclosed it inside the ViewMore component, but it tends to flicker when i start typing in the below textfield.
RN version: 0.46.4

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10921436/35047557-52ed55ce-fbc0-11e7-8e5c-a7a4a2184401.gif)
Please find the attached gif of the issue.

**Comment by nlt2390** [comment]
@Thanmai-C hi, could u provide ur android version + ur code ? I've tested on Android 5.0.0, 6.00 as well as IOS but didn't see this issue.

**Comment by Thanmai-C** [comment]
Android version 7.1
Device:  Nexus 5X
Snippet:
<ViewMoreText
						renderTimeout={50}
						numberOfLines={5}
						renderViewMore={this.renderViewMore}
						renderViewLess={this.renderViewLess}>
						<Text style={styles.desc}>{this.state.mediaData.description}</Text></ViewMoreText>

renderViewMore(onPress) {
		return (
			<Text onPress={onPress} style={{ color: "#c1c1c1" }}>
				View more
      </Text>
		);
	}
	renderViewLess(onPress) {
		return (
			<Text onPress={onPress} style={{ color: "#c1c1c1" }}>
				View less
      </Text>
		);
	}

**Comment by Thanmai-C** [comment]
I tested on android 6.0, 7.0, 7.1
Attached a code snippet of the usage in my project, please check and let me know.
[ViewMoreTextSnippet.txt](https://github.com/nlt2390/react-native-view-more-text/files/1641682/ViewMoreTextSnippet.txt)

**Comment by Thanmai-C** [comment]
Any fix for this??

**Comment by nlt2390** [comment]
@Thanmai-C hi, sry for late reply, I had a busy week. Anyway, I've had a look at ur code, these code lines seem to cause the issue:

```javascript
<TextField
  value={this.state.commentPost}
  onChangeText={text => {
     this.setState({ commentPost: text });
  }}
  ...
/>

<ViewMoreText
  <Text style={styles.desc}>{this.state.mediaData.description}</Text>
</ViewMoreText>
```

Everytime the value inside input changes, it make the state changing and the whole view is re-rendered. To fix this, u can take "commentPost" out of state and remove the property "value=" inside <TextField/>

```javascript
<TextField
  onChangeText={text => this.commentPost = text}
  ...
/>
```

hope this helps.

**Comment by Thanmai-C** [comment]
Thank u @nlt2390 , let me check and get back

**Comment by Thanmai-C** [comment]
It works, thank u
