### ISSUE TITLE
iOS: Works in Debug mode, not in Release mode

### ISSUE THREAD

**Issue by emcemcemc** [nlt2390/react-native-view-more-text#17]
Hi, 

When using multiple (3) ViewMores in a single component, they operate correctly for an iOS app in Debug mode. However when I change to Release mode, only the first 1 or 2 ViewMores will render. The ones that don't render still truncate the text, they just don't show the Read More button. Any ideas as to why this could be happening? The same problem occurrs when using expo/react-native-read-more library.

Thanks!

**Comment by nlt2390** [comment]
@emcemcemc Hi, can u send me ur code ?
