### ISSUE TITLE
View Read more is shown when not supposed

### ISSUE THREAD

**Issue by dsah** [nlt2390/react-native-view-more-text#18]
Hi, 
I have a large number of list and in that I am showing text with ability to show vewMore and viewLess, using this library works fine if I have very few number of list item but fails on anything more than couple of list items. Please have a look on attachment. I am using import { List, ListItem, Button } from 'react-native-elements'. Inside each listItem, i use react-native-view-more library.

![simulator screen shot - iphone 6 - 2018-02-20 at 20](https://user-images.githubusercontent.com/7278917/36416845-665e93b0-167e-11e8-94ef-aea2911d299d.png)

**Comment by dsah** [comment]
In attached image, you can see randomly Read more appears even though it hasn't reached the end of line, I am using numberOfLines{1} props.

**Comment by nlt2390** [comment]
@dsah Hi, plz paste ur code here too. Thanks.

**Comment by dsah** [comment]
import React, { Component } from 'react';
import { Text, View, ScrollView, FlatList } from 'react-native';
import { connect } from 'react-redux';
import { List, ListItem, Button } from 'react-native-elements';
import ViewMoreText from 'react-native-view-more-text';

class Help extends Component {

  _keyExtractor = (item, index) => index;

  renderViewMore = (handlePress) => {
        return (
          <Text style={{color: '#BDBDBD', marginTop: 5}} onPress={handlePress}>
            Read more
          </Text>
        );
      }

  renderViewLess = (handlePress) => {
    return (
      <Text style={{color: '#BDBDBD', marginTop: 5}} onPress={handlePress}>
        Read less
      </Text>
    );
  }

  renderCommentTxt(item, index){
    return (
        <ViewMoreText
          numberOfLines={1}
          renderViewMore={this.renderViewMore}
          renderViewLess={this.renderViewLess}
          >
          <Text>{item.comment}</Text>
        </ViewMoreText>
    );
  }

  renderItem(item, index) {
    return (
      <ListItem
        title={this.renderCommentTxt(item)}
        titleStyle={{width: 250, fontSize: 14, paddingLeft:0, marginLeft:0, color:'#000'}}
        subtitleContainerStyle={{paddingTop: 5}}
        subtitle={
          <View style={{flexDirection: 'row', justifyContent: 'space-between', marginRight: 5}}>
            <View><Text style={{color: 'gray'}}>{item.postingTime}</Text></View>
            <View><Text style={{color: 'gray'}}>{item.userFullName}</Text></View>
          </View>
        }
        subtitleStyle={{fontSize: 12}}
        hideChevron
      />
    )
  }

  render() {
    const comments = Array(40).fill().map((item, index) => { return {postingTime: new Date().toDateString(), userFullName: 'Test User', comment: 'somecomment'+index}})
    return (
      <ScrollView>
      <View style={{flex:1, alignItems:'center', justifyContent: 'center'}}>
      <List containerStyle={{width: '100%'}}>
        <FlatList
          data={comments}
          refreshing={false}
          keyExtractor={this._keyExtractor}
          renderItem={({item, index}) => this.renderItem(item, index)}
        />
      </List>
      </View>
      </ScrollView>
    );
  }
}

export default connect(null , {})(Help);

**Comment by dsah** [comment]
You will notice after 10th list item, it starts to show read more.

**Comment by nlt2390** [comment]
@dsah Hi, I don't see <ViewMoreText /> code is used in ur code.

**Comment by dsah** [comment]
`import React, { Component } from 'react';
import { Text, View, FlatList } from 'react-native';
import { connect } from 'react-redux';
import { List, ListItem, Button } from 'react-native-elements';
import ViewMoreText from 'react-native-view-more-text';

class Help extends Component {

_keyExtractor = (item, index) => index;

renderViewMore = (handlePress) => {
    return <Text style={{color: '#BDBDBD', marginTop: 5}} onPress={handlePress}>Read more</Text>;
}

renderViewLess = (handlePress) => {
  return <Text style={{color: '#BDBDBD', marginTop: 5}} onPress={handlePress}>Read less</Text>;
}

renderCommentTxt(item, index){
  return <ViewMoreText numberOfLines={1} renderViewMore={this.renderViewMore} renderViewLess={this.renderViewLess}><Text>{item.comment}</Text></ViewMoreText>;
}

renderItem(item, index) {
  return (
    <ListItem
      title={this.renderCommentTxt(item)}
      titleStyle={{width: 250, fontSize: 14, paddingLeft:0, marginLeft:0, color:'#000'}}
      subtitleContainerStyle={{paddingTop: 5}}
      subtitle={
        <View style={{flexDirection: 'row', justifyContent: 'space-between', marginRight: 5}}>
          <View><Text style={{color: 'gray'}}>{item.postingTime}</Text></View>
          <View><Text style={{color:'gray'}}>{item.userFullName}</Text></View>
        </View>
      }
      subtitleStyle={{fontSize: 12}}
      hideChevron
    />
  )
}

render() {
  const comments = Array(80).fill().map((item, index) => { return {postingTime: new Date().toDateString(), userFullName: 'Test User', comment: 'somecomment'+index}})
  return (
      <View style={{flex:1, alignItems:'center', justifyContent: 'center'}}>
        <List containerStyle={{width: '100%'}}>
          <FlatList
            data={comments}
            refreshing={false}
            keyExtractor={this._keyExtractor}
            renderItem={({item, index}) => this.renderItem(item, index)}
          />
        </List>
      </View>
    );
  }
}

export default connect(null , {})(Help);
`

**Comment by dsah** [comment]
I check the code is complete, the problem is also it's flickering when there is large number list items, looks like it is trying to calculate height or width before rendering text...

**Comment by dsah** [comment]
Also the performance is very bad when list grows.

**Comment by nlt2390** [comment]
Sry think I cannot help u with this. I don't know how `<ListItem />` works. May be u can try to use `<View>` and style it to look like `<ListItem />`.
