### ISSUE TITLE
Text flickers during rerender.

### ISSUE THREAD

**Issue by han4wluc** [nlt2390/react-native-view-more-text#20]
View flickers when view is rendered multiple times.

I believe it is because of those lines in react-native-view-more-text/index.js

```
  componentWillReceiveProps(nextProps) {
    this.resetData();

    this.setState({
      numberOfLines: null,
      opacity: 0,
    });
  }
```

![flicker](https://user-images.githubusercontent.com/8134740/37552876-09bac0f6-29f8-11e8-9e75-b84731c2e852.gif)

**Comment by nlt2390** [comment]
@han4wluc Hi, this is expected as the plugin needs to expand the text to measure the full height before cutting it off.

**Comment by marianrick** [comment]
@nlt2390 could we reopen this issue and try to remove the flickering? 

Depending on how much content will be cut off, the flickering can change the whole viewport, which seems to be a strange user experience. It looks like the app is not performant.

Maybe it could be a good idea to cut off the height using `overflow: 'hidden'` to avoid the changing height during the check of the original height?

**Comment by nlt2390** [comment]
@marianrick sry for late reply. I've updated to 1.4.4 to solve this issue, the whole text now just appear at once but it leaves a empty space on the screen when rendering. 
If u still find it imperfect, u can try to set opacity = 0 for ur whole content initially, and set to 1 after 200ms, by this time, everything on the screen should be done rendering.
