### ISSUE TITLE
Can't call setState (or forceUpdate) on an unmounted component

### ISSUE THREAD

**Issue by DavitVosk** [nlt2390/react-native-view-more-text#26]
Hi @nlt2390, hope you are doing well.

I have another here with the package. Can you please help to solve the problem.  

![image](https://user-images.githubusercontent.com/26307378/40845734-a5391daa-65c8-11e8-8d40-b96bcbd42882.png)

**Comment by DavitVosk** [comment]
Hi @nlt2390. I had fixed the problem. Can you please merge the subject changed comment in.

**Comment by DavitVosk** [comment]
Here I had included new prop `isUnmounted `

**Comment by nlt2390** [comment]
Hi @DavitVosk , in this case u can check isUnmounted in ur rendering code:

```javascript
  render(
    {
       !isUnmounted && <ViewMoreText />
    }
  )
```

And in case you want to make a contribution, please create a [Pull Request](https://help.github.com/articles/creating-a-pull-request/).

**Comment by nlt2390** [comment]
@DavitVosk I don't get it. Could u paste ur code here ?

**Comment by DavitVosk** [comment]
@nlt2390 Unfortunately I can't. The code is confidential. But the code is not important here. Look... you propose to use `!isUnmounted && <ViewMoreText />` code here. So `ViewMoreText` component will be called when `isUnmounted===false`. But in `ViewMoreText` component we have 2 `setIntervals`-s for calling `setState`. So I say that if that setStates are not called and finished, we will get an memory leak problem. That is why I propose to check the following: check component `unmount` status when the provided intervals are already passed.

**Comment by nlt2390** [comment]
@DavitVosk ok I understand ur issue. Let me find a way to remove those setTimeout function. Will keep u updated. Thanks.

**Comment by DavitVosk** [comment]
@nlt2390 Great, thanks

**Comment by nlt2390** [comment]
@DavitVosk hi, I've just published a new version with "setTimeout" functions are removed. Plz reinstall this package, thanks.

**Comment by DavitVosk** [comment]
@nlt2390 This version looks better and faster :) Thank you
