### ISSUE TITLE
the footview doesn't render when data is from server!

### ISSUE THREAD

**Issue by aiynmm** [nlt2390/react-native-view-more-text#27]
when fetch data from server in `componentDidMount()`, the footview doesn't render after have the data!

**Comment by nlt2390** [comment]
@aiynmm Hi, can u paste ur code here ?

**Comment by aiynmm** [comment]
```
componentDidMount() {
    fetch(...)
      .then((response) => {
            this.setState({
              data: response.data,
            })
        }
      ).catch((err) => {
      ...
    })
  };

render(){
   return(
      <View>
           ...
           <ViewMoreText
        numberOfLines={3}
        renderViewMore={this.renderViewMore}
        renderViewLess={this.renderViewLess}
        textStyle={{...}}
      >
        <Text>{this.state.data.xxx}</Text>
      </ViewMoreText>
           ...
      </View>
   );
}
```

View More (footview) didn't render!

**Comment by nlt2390** [comment]
@aiynmm plz try this: 
```javascript
  render(){
    if(this.state.data.xxx){
      return(
        <ViewMoreText>{this.state.data.xxx}</ViewMoreText>
      )
    }
  }
```

**Comment by aiynmm** [comment]
I have tried some code like this after reading your source code, but it didn't work. I was surprised that it's all right today... I didn't change anywhere!

**Comment by nlt2390** [comment]
@aiynmm the <ViewMoreText> must be mounted only when the data in the state is available. I think your data was cached somewhere in the app and it existed when <ViewMoreText> was mounted.

**Comment by aiynmm** [comment]
I have another problem, only `numberOfLines` prop is 1 ,and then view more (footer view) can be shown!

**Comment by nlt2390** [comment]
@aiynmm how many lines the text has when showing full ?

**Comment by aiynmm** [comment]
@nlt2390 Three or four lines, I have tried set `numberOfLines` equals two, the footer view of three lines can't be rendered,  if it's three, the footer of four lines can't be rendered either.

**Comment by nlt2390** [comment]
@aiynmm I cannot replicate this on my side. Try replace {this.state.data.xxx} with your full text and see if it happens, otherwise it's about the way you fetching data from API.

**Comment by aiynmm** [comment]
@nlt2390 I replace {this.state.data.xxx} with the full tex, then it still happens.

**Comment by aiynmm** [comment]
@nlt2390 Ha ha ha... I finally know where the problem is. I set `textStyle` props for view-more-text, in the `textStyle`, I set `fontFamily: 'PingFangSC-Medium',`, if like this, it will have a problem like I said above. After I remove `fontFamily: 'PingFangSC-Medium',`, it'll works fine.
