### ISSUE TITLE
Style doesn't work

### ISSUE THREAD

**Issue by vitorebatista** [nlt2390/react-native-view-more-text#3]
Hello!

I'm trying use different style into `ViewMoreText` (i.e `textAlign`) but It doesn't work. I think `ViewMoreText` could have a `customStyle` props to `Text` component. What do you think?

```
<ViewMoreText
  numberOfLines={20}
  renderViewMore={this.renderViewMore}
  renderViewLess={this.renderViewLess} >

  <Text style={styles.body}>{item.body}</Text>

</ViewMoreText>

const styles = StyleSheet.create({
  body: {
    fontSize:15,
    color:'#606060',
    lineHeight:24,
    marginRight:18,
    textAlign: 'justify'
  },
}
```

**Comment by nlt2390** [comment]
@vitorebatista Hi, I've tested your code in both IOS & Android and haven't got any issue so far. 

For `textAlign: 'justify'`, android doesn't support this style according to the [document](https://facebook.github.io/react-native/docs/text.html)

Hope this helps!

![IOS](http://image.prntscr.com/image/68c87fef15a9438c8f4448b5bbee7fd5.png) 
![Android](http://image.prntscr.com/image/068ce1c2fb994dfa9eb4c08ed2812f50.png)
