### ISSUE TITLE
view more button position and callback

### ISSUE THREAD

**Issue by jeffzing** [nlt2390/react-native-view-more-text#32]
![2018-10-12 3 04 13](https://user-images.githubusercontent.com/12021460/46853258-2471f400-ce30-11e8-8494-511bb4ddc9c4.png)
I made a unfold text view, but the unfold button will cover the text which makes the text looks like broken, I want it perfect,any solution?

**Comment by nlt2390** [comment]
@jeffzing  Can you try to wrap "unfold" with a <View/> inside renderViewMore function ?
