### ISSUE TITLE
How to selectable text?

### ISSUE THREAD

**Issue by dhanangpratama** [nlt2390/react-native-view-more-text#34]
I cannot select text in Text component which is already selectable.

Here's my code:

`<ViewMoreText
                            numberOfLines={15}
                            renderViewMore={this.renderViewMore}
                            renderViewLess={this.renderViewLess}
                        >
                            <Text selectable={true}>{content}</Text>
                        </ViewMoreText>`

I appreciate any help. ^__^
Thank you!

**Comment by rubanraj54** [comment]
Any update for this issue?

**Comment by nlt2390** [comment]
@rubanraj54  sry still busy at the office. Will check when i have time. Thanks.

**Comment by nlt2390** [comment]
@rubanraj54  hi, this looks like a react-native issue https://github.com/facebook/react-native/issues/13938

**Comment by snooplyin** [comment]
This is not a react-native issue. Setting the ability to long press copy from the Text component as such `<Text selectable={true}>{content}</Text>` does not work when inside of the `<ViewMoreText>` wrapper as OP suggests. Works outside of this component.
