### ISSUE TITLE
View more is not showing

### ISSUE THREAD

**Issue by pratik-ad** [nlt2390/react-native-view-more-text#39]
This is my code:

```
<ViewMoreText
  numberOfLines={1}
  renderViewMore={this.renderViewMore}
  renderViewLess={this.renderViewLess}
>
<Text style={styles.someStyle}>
{ this.state.textExist? this.state.text:""}
</Text>
</ViewMoreText>
```

I have to show text on some condition. The text is rendered when the condition becomes true, but View more is not rendered.
But if i make the text content fix, like below then it is working fine.
`<Text style={styles.someStyle}>
Any long long very long text 
</Text>`

All the other variables and functions are defined.

**Comment by pratik-ad** [comment]
I may have got to know the issue.

Actually the first time when it is rendered textExist is false so it renders the empty string thus no `View more` text, but after few seconds it renders the long text. This time text is long but somehow the condition which shows `View more` text is not updated.

**Comment by oromis300** [comment]
Hi, I have the same issue. Do you find a fix ?

**Comment by borasumer** [comment]
Can someone explain me why this issue is closed ? I don't see any fix.

**Comment by nlt2390** [comment]
> Hi, I have the same issue. Do you find a fix ?

This conditional checking should be outside:

```javascript
{ this.state.textExist && 
  <ViewMoreText
    numberOfLines={1}
    renderViewMore={this.renderViewMore}
    renderViewLess={this.renderViewLess}
  >
    <Text style={styles.someStyle}>
       {this.state.text}
    </Text>
  </ViewMoreText>
}
```
