### ISSUE TITLE
Its showing nested view error in using react-native-render-Html library

### ISSUE THREAD

**Issue by vivek751** [nlt2390/react-native-view-more-text#42]

**Comment by nlt2390** [comment]
@vivek751 plz paste ur code here

**Comment by vivek751** [comment]
![Screenshot 2019-11-28 at 4 08 53 PM](https://user-images.githubusercontent.com/31432394/69799527-72df7f00-11f9-11ea-96ea-0d59df3ba0e3.png)

**Comment by vivek751** [comment]
![Simulator Screen Shot - iPhone 7 - 2019-11-28 at 16 09 34](https://user-images.githubusercontent.com/31432394/69799561-7ffc6e00-11f9-11ea-96e9-d5168523d293.png)

**Comment by vivek751** [comment]
@nlt2390  Please help me out :(

**Comment by nlt2390** [comment]
@vivek751  sry but this plugin only supports text, not components
