### ISSUE TITLE
If i set numberOfLines = 3 then i have posted some blog Paragraph style that time first paragraph shown ReadMore and After Line show content 

### ISSUE THREAD

**Issue by vivek751** [nlt2390/react-native-view-more-text#43]

**Comment by vivek751** [comment]
![Screenshot 2020-03-16 at 12 30 45 PM](https://user-images.githubusercontent.com/31432394/76730810-04abd180-6782-11ea-9eee-6af8d19f5cf9.png)

**Comment by vivek751** [comment]
Hope you understand what i mean to say

**Comment by nlt2390** [comment]
@vivek751  plz post ur code here

**Comment by vivek751** [comment]
@nlt2390 here is my code

  <ViewMoreText numberOfLines={3} renderViewMore={renderViewMore} renderViewLess={renderViewLess}
                textStyle={{textAlign: 'left',paddingTop:6}}>
                    <Text allowFontScaling={allowFontScaling} style={convertedCSSStyles}>{ children }</Text>
            </ViewMoreText>

**Comment by nlt2390** [comment]
@vivek751 right now {children} only supports <Text> so if u pass a complex component like 
<View><Text></Text></View> it may not work properly

**Comment by vivek751** [comment]
@nlt2390 i just passed on Html Tag
