### ISSUE TITLE
Show More does not display always 

### ISSUE THREAD

**Issue by mihaelatd96** [nlt2390/react-native-view-more-text#7]
Show More does not display always when the text does not fit inside a view.

![screen shot 2017-10-30 at 09 44 13](https://user-images.githubusercontent.com/33216698/32159648-05ba3f1c-bd57-11e7-9213-b1849c3f7bc1.png)

**Comment by nlt2390** [comment]
Hi, can u paste a sample code here ?

**Comment by mihaelatd96** [comment]
Hello,
Yes. Here it is. The informations come from the server and the View size is given by the width and height of the device. The openModal function opens a modal with specific content.
              {this.state.singleEvent.notes?              <ViewMoreText              numberOfLines={6}              renderViewMore={()=>{return(<Text                style={{  marginTop: 6,                  color: 'black',textAlign:'right',                  fontSize: 10}}                onPress={(event)=>{              this.setState({contentModal:"EVENT_DETAILS"});              this.refs.CustomModal.openModal();}}>View More</Text>)}}>
              <Text                  style={{                  paddingLeft:5,                  paddingRight:5,                  color: '#545659',                  fontSize: 12,                  fontStyle: 'italic'                }}               textBreakStrategy="simple"               adjustsFontSizeToFit={false}               allowFontScaling={false}>                  {this.state.singleEvent.notes}              </Text>          </ViewMoreText>
    On Monday, October 30, 2017, 10:19:41 AM GMT+2, Liam N. <notifications@github.com> wrote:  
 
 
Hi, can u paste a sample code here ?

**Comment by CristinaNicolae** [comment]
I am having the same issue.

**Comment by nlt2390** [comment]
@mihaelatd96 @CristinaNicolae Hi sorry for late reply, was having a crazy busy week. I guess u missing calling `onPress` in side `renderViewMore`, i.e

```
renderViewMore={(**onPress**)=>{
    return(<Text style={...}               
    onPress={(event)=>{                                                                                       
      this.setState({contentModal:"EVENT_DETAILS"});                                                                                           
      this.refs.CustomModal.openModal();
      **onPress();**
}}
```
Hope this helps.

**Comment by massoul** [comment]
Hello!
Sorry for posting in this closed issue, but I have the same issue. It sometimes works, sometimes it has expanded the text and sometimes the "view more" text isn't shown at all.
I'm using your exact code example in the readme.

Does the component need some kind of key to get it function properly?
I've tried it but I can't get it to work.
Thanks for the help!

**Comment by nlt2390** [comment]
@massoul can u paste ur code here ?

**Comment by massoul** [comment]
This is inside my component:
`<View style={{marginLeft: 15, marginRight: 15}}>
              <Text style={styles.h3Text}>Beskrivning</Text>
              <ViewMoreText
                numberOfLines={3}
                renderViewMore={this.renderViewMore}
                renderViewLess={this.renderViewLess}
                textStyle={{ textAlign: "left" }}
              >
                <Text style={styles.text}>
                  {this.renderViewText()}
                </Text>
              </ViewMoreText>
            </View>`

And this is the renderViewText():
`renderViewText() {
    if(this.state.componentHasMounted) {
      return this.state.info.description;
    }
  }`

**Comment by massoul** [comment]
@nlt2390 By changing your code `this.shouldShowMore = true;` in resetData, I can get the view more/less to always show.
But I can't have it always collapsed from the beginning. It shows expanded or collapsed like before.

**Comment by nlt2390** [comment]
@massoul plz try this:

```javascript
<View...>
  <Text...>Beskrivning</Text>
  {this.renderViewText()}
</View>

renderViewText(){
  if(this.state.componentHasMounted) { 
    return(
      <ViewMoreText
          numberOfLines={3}
          renderViewMore={this.renderViewMore}
          renderViewLess={this.renderViewLess}
          textStyle={{ textAlign: 'left' }}
      >
        <Text style={styles.text}>
          {this.state.info.description}
        </Text>
      </ViewMoreText>
  }
}
```

**Comment by massoul** [comment]
@nlt2390 it works like a charm!!! thanks, you're awesome!!!

**Comment by nlt2390** [comment]
@massoul  glad to help :))

**Comment by witalobenicio** [comment]
I'm not able to show `renderViewMore` too and when I can show, it's just not expand it:

```
<ViewMoreText
                numberOfLines={3}
                renderViewMore={(onPress) => {
                  return (<View onPress={() => {onPress()}} style={{flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 10}}>
                    <Text style={{fontSize: 13, fontWeight: '600', color: '#000'}}>Ver Mais</Text>
                    <Image style={{width: 14, height: 14, marginLeft: 5, tintColor: '#000'}} source={Images.iconChevronDown}/>
                  </View>)
                }}
                renderViewLess={(onPress) => {
                  return (<View onPress={() => {onPress()}} style={{flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 10}}>
                    <Text style={{fontSize: 13, fontWeight: '600', color: '#000'}}>Ver Menos</Text>
                    <Image style={{width: 14, height: 14, marginLeft: 5, tintColor: '#000'}} source={Images.iconChevronUp}/>
                  </View>)
                }}>
                <Text style={styles.charValue}>{product.description || testText}</Text>
              </ViewMoreText>
```

**Comment by nlt2390** [comment]
@witalobenicio  plz try 
```javascript
  if(product.description){
    return(
      <ViewMoreText>... </ViewMoreText>
    )
  }
```

**Comment by VitaliiK91** [comment]
Hi @nlt2390 I am experiencing same issue. It seems to work properly in debug mode, but in release mode READE MORE is not rendered. Here is my code snippet:
```js
class LongDescription extends PureComponent {
	render() {
		const { desc, numberOfDescriptionLines, themeParams } = this.props;
		if (!desc) {
			return null;
		}
		return (
			<View style={styles.ViewMoreContainer}>
				<ViewMoreText
					numberOfLines={
						color.themeFor(themeParams, 'numberOfDescriptionLines') ||
						numberOfDescriptionLines
					}
					renderViewMore={onPress =>
						(
							<Text
								onPress={onPress}
								style={[styles.ViewMoreLabel, color.themeFor(themeParams, 'viewMoreTextStyle')]}
							>
								READ MORE
							</Text>
						)
					}
					renderViewLess={onPress =>
						(
							<Text
								onPress={onPress}
								style={[styles.ViewMoreLabel, color.themeFor(themeParams, 'viewMoreTextStyle')]}
							>
								READ LESS
							</Text>
						)
					}
					textStyle={[styles.ParsedDescriptionContainer, color.themeFor(themeParams, 'descriptionTextStyle')]}
				>
					<ParsedText
						parse={[...TitleHelper.PATTERNS, ...(color.themeFor(themeParams, 'detailsParsedTextPatterns') || [])]}
					>
						{desc}
					</ParsedText>
				</ViewMoreText>
			</View>
		);
	}
}
```
I debugged the component and it appears that `renderFooter()` always returns null.
Any ideas?
Thanks
