### ISSUE TITLE
Can't be used with different versions of react-native

### ISSUE THREAD

**Issue by EmilScherdin** [nlt2390/react-native-view-more-text#9]
Hi! 
This seems like a great package but I have an issue getting started.

It keeps complaining that I have two versions of `react-native` in my `node_modules`. That is because the package requires a fixed version of `react-native` (and react, prop-types).

The problem:
https://github.com/nlt2390/react-native-view-more-text/blob/master/package.json#L24
```
"dependencies": {
    "prop-types": "15.6.0",
    "react": "16.0.0",
    "react-native": "0.50.1"
  }
```

Maybe we can do something like this?
```
"dependencies": {
    "prop-types": "*",
    "react": "*",
    "react-native": "*"
  }
```

Using: 
React-native: 49.5
React: 16.0.0
Prop-types: ^15.5.10

**Comment by nlt2390** [comment]
@EmilScherdin  Hi, thanks for raising this issue. I've just updated package.json, plz try again and let me know if the issue still happens.

**Comment by EmilScherdin** [comment]
@nlt2390 Thanks, but it's quite not working. 😬

It will still throw an error if you don't have the same version due to it's still it's in dependencies with a fixed version. Because it will always be in a react-native project we could remove `react` & `react-native` as dependencies or *only* have them in `peerDependencies` because the project will always include them anyway. Thoughts? 

And for `prop-types` there documentation says a package should add it to dependencies but with a carrot range, like: `^15.x.x`. Can we use `15.x` or does the package require `16.x`. Thinking that lower is better? 🤔
https://github.com/facebook/prop-types#how-to-depend-on-this-package

**Comment by EmilScherdin** [comment]
Added a PR for this: #10
